# Generated by Django 2.1.5 on 2019-02-21 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190221_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 23, 37, 39, 76964)),
        ),
    ]
