# Generated by Django 2.1.5 on 2019-02-25 14:49

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190221_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('particular', models.CharField(max_length=35)),
                ('summary', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=1, max_digits=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date_cust', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 20, 19, 46, 118247))),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 20, 19, 46, 118247)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
