# Generated by Django 2.1.5 on 2019-03-11 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20190311_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 14, 35, 40, 562742)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 14, 35, 40, 562742)),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='mobile_number',
            field=models.CharField(max_length=13),
        ),
    ]
