# Generated by Django 2.1.5 on 2019-03-13 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190311_1413'),
        ('customers', '0007_auto_20190312_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rate',
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='order', to='products.Menu'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='customer',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 25, 38, 405114)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='summary',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 25, 38, 405114)),
        ),
    ]
