# Generated by Django 2.1.5 on 2019-03-13 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20190313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 26, 15, 937209)),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 26, 15, 937209)),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='particular',
            field=models.ManyToManyField(blank=True, related_name='particular', to='products.Menu'),
        ),
    ]
