# Generated by Django 2.1.5 on 2019-03-13 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20190313_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 33, 29, 63817)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gym',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 33, 29, 63817)),
        ),
    ]
