# Generated by Django 2.1.5 on 2019-03-13 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20190313_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 34, 48, 310214)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gym',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='customer',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 16, 34, 48, 312213)),
        ),
    ]
