# Generated by Django 2.1.5 on 2019-03-13 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20190313_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='male',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 20, 23, 46, 981174)),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 13, 20, 23, 46, 981174)),
        ),
    ]
