# Generated by Django 2.1.5 on 2019-03-16 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20190316_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 23, 4, 23, 324738)),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='date_cust',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 23, 4, 23, 324738)),
        ),
    ]
