# Generated by Django 2.1.5 on 2019-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('mobile_number', models.CharField(max_length=12)),
                ('suggestions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
