# Generated by Django 2.1.5 on 2019-02-13 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0035_auto_20190213_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 22, 39, 27, 697240)),
        ),
    ]
