# Generated by Django 2.1.5 on 2019-02-21 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0036_auto_20190213_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 12, 25, 12, 447209)),
        ),
    ]
