# Generated by Django 2.1.5 on 2019-02-21 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0037_auto_20190221_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 12, 29, 14, 576934)),
        ),
    ]
