# Generated by Django 2.1.5 on 2019-02-21 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0041_auto_20190221_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 23, 11, 50, 35146)),
        ),
    ]
