# Generated by Django 2.1.5 on 2019-02-25 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0044_auto_20190221_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 20, 19, 46, 19538)),
        ),
    ]
