# Generated by Django 2.1.5 on 2019-03-11 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0046_auto_20190311_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 11, 14, 35, 40, 484645)),
        ),
    ]
