# Generated by Django 2.1.5 on 2019-03-12 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0047_auto_20190311_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 12, 13, 58, 41, 736960)),
        ),
    ]
