# Generated by Django 2.1.5 on 2019-03-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0053_auto_20190313_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='serial',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 14, 12, 36, 29, 872274)),
        ),
    ]
