# Generated by Django 2.1.5 on 2019-03-16 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0054_auto_20190314_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 21, 19, 53, 357303)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
