# Generated by Django 2.1.5 on 2019-03-16 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0056_auto_20190316_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 21, 23, 32, 890913)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
