# Generated by Django 2.1.5 on 2019-03-16 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0060_auto_20190316_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 23, 31, 50, 727585)),
        ),
    ]
